// Generated by uniffi-bindgen-react-native
#include "react-native-matrix-rust-sdk.h"
#include "generated/matrix-sdk-ffi.hpp"

namespace reactnativematrixrustsdk {
	using namespace facebook;

	// TODO Remove `multiply` after seeing this work on iOS and Android.
	double multiply(double a, double b) {
		return a * b;
	}

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeMatrixSdkFfi::registerModule(runtime, callInvoker);
		return false;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime, uint8_t b) {
		return false;
	}
}