#ifndef REACTNATIVEMATRIXRUSTSDK_H
#define REACTNATIVEMATRIXRUSTSDK_H
// Generated by uniffi-bindgen-react-native
#include <cstdint>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvoker.h>

namespace reactnativematrixrustsdk {
  using namespace facebook;

  // TODO Remove `multiply` after seeing this work on iOS and Android.
  double multiply(double a, double b);

  uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker);
  uint8_t cleanupRustCrate(jsi::Runtime &runtime, uint8_t b);
}

#endif /* REACTNATIVEMATRIXRUSTSDK_H */