// Generated by uniffi-bindgen-react-native
#import "MatrixRustSdk.h"

namespace uniffi_generated {
    using namespace facebook::react;
    /**
    * ObjC++ class for module 'NativeMatrixRustSdk'
    */
    class JSI_EXPORT NativeMatrixRustSdkSpecJSI : public ObjCTurboModule {
    public:
        NativeMatrixRustSdkSpecJSI(const ObjCTurboModule::InitParams &params);
        std::shared_ptr<CallInvoker> callInvoker;
    };

    static facebook::jsi::Value __hostFunction_MatrixRustSdk_installRustCrate(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
        auto& tm = static_cast<NativeMatrixRustSdkSpecJSI&>(turboModule);
        auto jsInvoker = tm.callInvoker;
        uint8_t result = matrixrustsdk::installRustCrate(rt, jsInvoker);
        return facebook::jsi::Value(rt, result);
    }
    static facebook::jsi::Value __hostFunction_MatrixRustSdk_cleanupRustCrate(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
        uint8_t result = matrixrustsdk::cleanupRustCrate(rt);
        return facebook::jsi::Value(rt, result);
    }

    NativeMatrixRustSdkSpecJSI::NativeMatrixRustSdkSpecJSI(const ObjCTurboModule::InitParams &params)
        : ObjCTurboModule(params), callInvoker(params.jsInvoker) {
            this->methodMap_["installRustCrate"] = MethodMetadata {1, __hostFunction_MatrixRustSdk_installRustCrate};
            this->methodMap_["cleanupRustCrate"] = MethodMetadata {1, __hostFunction_MatrixRustSdk_cleanupRustCrate};
    }
} // namespace uniffi_generated

@implementation MatrixRustSdk
RCT_EXPORT_MODULE()

// Don't compile this code when we build for the old architecture.
#ifdef RCT_NEW_ARCH_ENABLED
- (NSNumber *)installRustCrate {
    @throw [NSException exceptionWithName:@"UnreachableException"
                        reason:@"This method should never be called."
                        userInfo:nil];
}

- (NSNumber *)cleanupRustCrate {
    @throw [NSException exceptionWithName:@"UnreachableException"
                        reason:@"This method should never be called."
                        userInfo:nil];
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
    return std::make_shared<uniffi_generated::NativeMatrixRustSdkSpecJSI>(params);
}
#endif

@end