// Generated by uniffi-bindgen-react-native
import installer from './NativeMatrixRustSdk';

// Register the rust crate with Hermes
installer.installRustCrate(true);

export function multiply(a: number, b: number): number {
  return installer.multiply(a, b);
}

// Export the generated bindings to the app.
export * from './generated/rondpoint';